#!/bin/zsh

######################################
# Resize Mode
######################################
# increase window size
resize  <  j : yabai -m window --resize left:-80:0  || yabai -m window --resize right:-80:0
resize  <  k : yabai -m window --resize bottom:0:80 || yabai -m window --resize top:0:80
resize  <  i : yabai -m window --resize top:0:-80   || yabai -m window --resize top:0:80 ||  yabai -m window --resize bottom:0:-80
resize  <  l : yabai -m window --resize right:80:0  || yabai -m window --resize left:80:0

# decrease window size
resize  <  shift - l : yabai -m window --resize left:80:0
resize  <  shift - i : yabai -m window --resize bottom:0:-80
resize  <  shift - k : yabai -m window --resize top:0:80
resize  <  shift - j : yabai -m window --resize right:-80:0

# # move window
# resize  <  alt - j : yabai -m window --move rel:-40:0 # left
# resize  <  alt - k : yabai -m window --move rel:0:40  # down
# resize  <  alt - i : yabai -m window --move rel:0:-40 # up
# resize  <  alt - l : yabai -m window --move rel:40:0  # right

######################################
# Navigation
######################################
resize  <  lalt - j : yabai -m window --focus west || yabai -m window --focus last
resize  <  lalt - k : yabai -m window --focus south || yabai -m window --focus north
resize  <  lalt - i : yabai -m window --focus north || yabai -m window --focus south
resize  <  lalt - l : yabai -m window --focus east || yabai -m window --focus first
