#!/bin/zsh

######################################
# Spaces
######################################
# Focus Space
lalt - 1            : yabai -m space --focus 1
lalt - 2            : yabai -m space --focus 2
lalt - 3            : yabai -m space --focus 3
lalt - 4            : yabai -m space --focus 4
lalt - 5            : yabai -m space --focus 5
lalt - 6            : yabai -m space --focus 6
lalt - 7            : yabai -m space --focus 7
lalt - 8            : yabai -m space --focus 8
lalt - 9            : yabai -m space --focus 9
lalt - 0            : yabai -m space --focus 10
# Focus prev, next and recent
cmd + ctrl - left   : yabai -m space --focus prev
cmd + ctrl - right  : yabai -m space --focus next
lalt - q            : yabai -m space --focus prev
lalt - r            : yabai -m space --focus next
lalt - t            : yabai -m space --focus recent

# Send window to Space and follow
# To prev, next and recent
shift + lalt - q : yabai -m window --space prev && yabai -m space --focus prev
shift + lalt - r : yabai -m window --space next && yabai -m space --focus next
shift + lalt - t : yabai -m window --space recent && yabai -m space --focus recent

shift + lalt - 1 : yabai -m window --space  1 && yabai -m space --focus 1
shift + lalt - 2 : yabai -m window --space  2 && yabai -m space --focus 2
shift + lalt - 3 : yabai -m window --space  3 && yabai -m space --focus 3
shift + lalt - 4 : yabai -m window --space  4 && yabai -m space --focus 4
shift + lalt - 5 : yabai -m window --space  5 && yabai -m space --focus 5
shift + lalt - 6 : yabai -m window --space  6 && yabai -m space --focus 6
shift + lalt - 7 : yabai -m window --space  7 && yabai -m space --focus 7
shift + lalt - 8 : yabai -m window --space  8 && yabai -m space --focus 8
shift + lalt - 9 : yabai -m window --space  9 && yabai -m space --focus 9
shift + lalt - 0 : yabai -m window --space 10 && yabai -m space --focus 10